### ISSUE TITLE
EmployeeDump.aspx Filterfehler bei Statistikfunktionen

### ISSUE THREAD

**Issue by dersebbel** [geraldbaeck/NIUsLittleHelper#17]
**EmployeeDump.aspx Filterfehler bei Statistikfunktionen**
Betroffene Datei(en): **EmployeeDump.aspx** (+ Dependenz  _jquery.dataTables.min.js_)

- Der Benutzer öffnet Liste/Ausdruck, berechnet die RD-Dienstleistung über die Statistikfunktion. Anschließend möchte der Benutzer die RD-Dienstleistung über das Textfeld filtern. Es passiert nichts und folgender Fehler wird ausgeworfen:
`Uncaught TypeError: Cannot read property 'includes' of undefined @ EmployeeDump.js:203`

- Der Benutzer öffnet Liste/Ausdruck und filtert einige Mitarbeiter über z.B die DNr ohne vorher die RD-Dienstleistungen berechnet zu haben. Er möchte nun nur für die (bereits gefiltert) angezeigten Mitarbeiter die RD-Dienstleistungen berechnen. Das DataTable verschwindet komplett und folgende Fehler werden ausgeworfen:
`Uncaught TypeError: Cannot read property 'sDefaultContent' of undefined @ jquery.dataTables.min.js:17`
`Uncaught TypeError: datatable.column is not a function @ EmployeeDump.js:252`

**Comment by spind42** [comment]
Sollte jetzt behoben sein mit r541e44d7b1ce69be2a30a3a5ec513d2a3132181a
