### ISSUE TITLE
Umlaute bei Memo über Liste/Ausdruck falsch encodiert

### ISSUE THREAD

**Issue by dersebbel** [geraldbaeck/NIUsLittleHelper#19]
**Umlaute bei Memo über Liste/Ausdruck falsch encodiert**
Betroffene Datei(en): **tools.js**

- Der Benutzer schreibt ein oder mehrere Memos über Liste/Ausdruck, allerdings werden Umlaute anschließend im Memosystem falsch encodiert angezeigt (unleserlich).

_Welches Encoding, ANSI escape chars? ..._

**Comment by spind42** [comment]
gefixed mit 840aff7c05f40cd98a36bad31cf2aeb51c5f07ea -> es werden per javascript funktion escape encodierte werte übernommen, deswegen jetzt escape eingebaut in den code
