### ISSUE TITLE
2-spaltige Dienstpläne bringen die Statistik zum Absturz

### ISSUE THREAD

**Issue by dersebbel** [geraldbaeck/NIUsLittleHelper#22]
**2-spaltige Dienstpläne bringen die Statistik zum Absturz**
Betroffene Datei(en): **EmployeeDutyStatistic.js**

**Status: Skript funktioniert aufgrund Übergangslösung, Fehler an sich nicht behoben.**

Gewisse Dienstpläne haben nur 2 Spalten (z.B ÄFD hat nur Fahrer und Azubi Positionen), das Skript versucht dann für die Spalte "Bemerkung" ebenfalls eine Berechnung durchzuführen und stürzt ab.

**Übergangslösung:** try-catch error routine in die SAN2 Berechnung eingebaut sodass, wenn diese einen Fehler aufgrund des oben beschriebenen Problems ausgibt, nicht das ganze Script abstürzt.

**To-Do:** Berechnungsfunktion davon abhalten bei 2-spaltigen Dienstplänen die 3te Spalte (in diesem Fall "Bemerkung" nicht "SAN2") ebenfalls auszuwerten. Optimalerweise auch die Positionsnamen für die Berechnung berücksichtigen, z.B im Dienstplan BT-SAN ist Reserve != SAN2.

**Derzeit abgefangene Fehlermeldung:**
`Uncaught Error: Syntax error, unrecognized expression: ÄFD (19:00-07:00)|ÄFD|1 @ HTMLTableCellElement.<anonymous> (VM5474 EmployeeDutyStatistic.js:115)`

**Comment by spind42** [comment]
ich schlage vor einfach einzubauen:

tableType.includes('KTW') || tableType.includes('RKS') || tableType.includes('RKL') || tableType.includes('RKP')  
//RD CODE
analog zum ÄFD
tableType.includes('ÄFD')
