### ISSUE TITLE
Wunschmeldung: > Nachname in der Statistik

### ISSUE THREAD

**Issue by geraldbaeck** [geraldbaeck/NIUsLittleHelper#23]
KollegInnen die noch nicht fixiert sind, tauchen als "Wunschmeldung: > Nachname" in der Statistik

![pasted image at 2017_04_19 09_08 am](https://cloud.githubusercontent.com/assets/199418/25182509/268c7d02-2515-11e7-80ce-828aa483184d.png)

**Comment by dersebbel** [comment]
Fixed 952222a
