### ISSUE TITLE
Sende to Team

### ISSUE THREAD

**Issue by spind42** [geraldbaeck/NIUsLittleHelper#24]
"Send Team". Auf größeren Ambulanzen einer eigens ausgewählten Gruppe an Leuten eine Mail schicken können. Ein button zum Aktivieren, Checkboxen zum Auswählen der Mitarbeiter und das ganze wird einfach ins Mailprogramm exportiert.

**Comment by geraldbaeck** [comment]
Wir müssten dazu im Hintergund jedes einzelne Profil abfrage, um an die email adresse zu kommen. Technisch kein Problem, aber bei großen Ambulanzen eine Menge requests.

**Comment by geraldbaeck** [comment]
done
