### ISSUE TITLE
Typo in Play Store

### ISSUE THREAD

**Issue by schwindp** [geraldbaeck/NIUsLittleHelper#26]
![niu_helper](https://user-images.githubusercontent.com/187595/27024708-fb2e555a-4f57-11e7-9178-f08b9acd364f.png)
See Image (extension name is missing an 'l'). Don't know if it's possible to rename the extension without jumping through hoops.

**Comment by geraldbaeck** [comment]
Ich könnte mich dafür in den Hintern beißen, aber leider nicht änderbar, außer wir machen ein neues Store Item.

**Comment by schwindp** [comment]
Ok, dann hat sich meine Ahnung bestätigt -> RESOLVED WONTFIX
