### ISSUE TITLE
Pflichtfortbildungsprüfung

### ISSUE THREAD

**Issue by spind42** [geraldbaeck/NIUsLittleHelper#30]
Bei der Prüfung der Pflichtfortbildung sollte der Kurs A03241 berücksichtigt werden - der Anrechnungskurs für die Pflichtfortbildungen

**Comment by spind42** [comment]
Frage ist, ob sich der Aufwand rechnet?

**Comment by dersebbel** [comment]
checkCourseAttendance mit b193a03a074702eb6bf39b02cdc7b3275a44c2fb angepasst dass sich Kurse über die ABZ-Nummer auswerten lassen. Derzeit allerdings aufgrund eines NIU-Bug noch nicht möglich, LV EDV wurde bereits informiert.

**Comment by spind42** [comment]
Ich denke wir werden diesen NIU "Bug" wohl akzeptieren müssen und wohl einen Workaround bauen. Das ganze Projekt ist ja ein Workaround *g*

**Comment by dersebbel** [comment]
Wurde seitens LV EDV behoben und implementiert. d52ad4673d7834cf6b025a92d728bf39064a4230
