### ISSUE TITLE
Ein/Ausblenden Defekt bei der Kurssuche

### ISSUE THREAD

**Issue by spind42** [geraldbaeck/NIUsLittleHelper#33]
Beim Ein- und Ausblenden der Kurssuche gibt es Probleme. Die Links zum Ein- und Ausblenden sind falsch gesetzt.

**Comment by dersebbel** [comment]
Mit f9c1fb1b084e42fc7033e478dcd55e013ab4e969 behoben.
Funktioniert nun sowohl unter "Meine Kurse" als auch unter "Kurssuche"
