### ISSUE TITLE
Neues Kursauswahlfeld "nur §51 Rezertifizierungen"

### ISSUE THREAD

**Issue by schwindp** [geraldbaeck/NIUsLittleHelper#34]
maybe? Mit der nun jährlich nötigen Rezertifizierung sicherlich gerne genutzt.

Abgesehen davon: Ein Stückchen Whitespace **nach** dem Text (und somit vor dem nächsten Kästchen) hilft der Optik auf die Sprünge :+1:

**Comment by dersebbel** [comment]
Mit b07c6ea7824d5e2e5b2f85977c4d62a1a5537961 implementiert. Danke!
