### ISSUE TITLE
Neues Export-to-iCal Feature / HOW?

### ISSUE THREAD

**Issue by schwindp** [geraldbaeck/NIUsLittleHelper#37]
Morgen zusammen,
danke für das frische Feature auf der "Startseite", ich find das schon recht praktisch. Aber: Wie soll das genau funktionieren? Hab's auf Chrome unter MacOS getestet, da blitzt was im Chrome auf, aber im Kalender ist nichts zu sehen. Auch kein Download, kein sonstwas. Ok, mal Outlook geklickt: Selbes Verhalten.

Chrome 61/Linux: Genauso, irgendwas tut sich, aber nichts effektives.
Wie kann man Euch hier beim Testen unterstützen?

**Comment by geraldbaeck** [comment]
Gibt Deine Console Fehler aus? Aussehen sollte es so: 
![niu niu menu](https://user-images.githubusercontent.com/199418/30532835-a60481f2-9c56-11e7-8f2c-2e9dd19e643f.png)

**Comment by schwindp** [comment]
- Sieht aus wie oben, nur ohne Google.
- Keine Fehler zu sehen: 
<img width="609" alt="bildschirmfoto 2017-09-18 um 09 59 35" src="https://user-images.githubusercontent.com/187595/30533154-27eb8854-9c58-11e7-9cee-37d793f52107.png">
- Das ganze auf einem frisch reingekommenen Version 61.0.3163.91 (Offizieller Build) (64-Bit)

**Comment by geraldbaeck** [comment]
Schwierig zu debuggen. Hast Du andere Extensions laufen, zb Ad-Blocker oder Disconnect.

**Comment by schwindp** [comment]
ublock Origin, ja. Uuuuund <tadaa.wav> nun tut's. Könnte man noch an passender Stelle drauf hinweisen.
Dankeschön!

**Comment by geraldbaeck** [comment]
Lustig, ich verwende auch ublock Origin 1.14.8. Bei mir wurde nichts geblockt. Wahrscheinlich liegt es sogar nur am verwendeten Filter.

**Comment by dersebbel** [comment]
Bei mir funktioniert es auch sowohl mit UBlock als auch Adblock Plus.
