### ISSUE TITLE
ABZ Kurs-Termine werden mit falschem Datum ins Outlook exportiert.

### ISSUE THREAD

**Issue by geraldbaeck** [geraldbaeck/NIUsLittleHelper#38]
Derzeit nicht duplizierbar. Muss es auf einer Windowsmaschine testen.

**Comment by dersebbel** [comment]
Auf Windows 10/Outlook 2016 nicht replizierbar

**Comment by geraldbaeck** [comment]
weiterhin nicht replizierbar, keine weiteren Fehlermeldungen erhalten
