### ISSUE TITLE
Dropdown bei Kursanmeldung leer

### ISSUE THREAD

**Issue by fs1** [geraldbaeck/NIUsLittleHelper#40]
links mit aktivierter Erweiterung, rechts deaktiviert.
![grafik](https://user-images.githubusercontent.com/1917852/30853518-5506f226-a2af-11e7-9cc4-a7d55cad5375.png)

Version: 0.48.4

**Comment by dersebbel** [comment]
Hallo, das liegt daran dass es sich um ein Autocomplete Feld handelt - einfach einen Teil des Namens oder die Dienstnummer eingeben. LG
