### ISSUE TITLE
Single Libraries

### ISSUE THREAD

**Issue by geraldbaeck** [geraldbaeck/NIUsLittleHelper#41]
Derzeit verwenden wir 2-3 verschiedene jquery Libraries und zumindest 2 verschiedene Versionen von moment.js => zusammenführen

**Comment by dersebbel** [comment]
Was hältst du davon generell für alle Content-Scripts auf die volle JQuery umzusteigen und uns die light Version zu sparen?

**Comment by geraldbaeck** [comment]
Ja sollten wir machen
