### ISSUE TITLE
Wagenkontrollzettel

### ISSUE THREAD

**Issue by geraldbaeck** [geraldbaeck/NIUsLittleHelper#45]
Für fixierte Dienste könnte man sich einen vorausgefüllten Wagenkontrollzettel ausdrucken.

**Comment by sebastiankuttnig** [comment]
Ist halt nicht sonderlich ökologisch sich Wagenkontrollzettel zu Hause auszudrucken wenn diese massenweise auf den Dienststellen aufliegen. ;-)

**Comment by danielsteiner** [comment]
Es ist allgemein nicht sonderlich ökologisch die Dinger zu haben - vor allem wenn sie eh "leer" abgegeben werden

**Comment by geraldbaeck** [comment]
ich dachte eher daran sich ein paar mitzunehmen und drauf zu drucken




----
DI Gerald Bäck | fb <https://facebook.com/geraldbaeck> | blog
<http://www.baeck.at/> | devblog <http://dev.baeck.at> | +43 664 5107761
<+436645107761>

**Comment by geraldbaeck** [comment]
zu aufwändig, zu wenig Nutzungspotenzial
