### ISSUE TITLE
Filter "Nur offene Kurse" schlägt fehlt bei Nicht-Angabe einer Anzahl offener Plätze

### ISSUE THREAD

**Issue by schwindp** [geraldbaeck/NIUsLittleHelper#51]
Ergebnis: Kurs wird nicht angezeigt

Beispielkurs: 18720102

**Comment by sebastiankuttnig** [comment]
Der Filter heißt ja "Nur Kurse mit freien Plätzen", nachdem aber für den jeweiligen Kurs seitens ABZ noch keine Plätze kontingentiert wurden ist eine Anmeldung meines Wissens sowieso noch nicht möglich/vorgesehen. Ich würde das demnach eher verwirrend finden wenn wir diese Kurse ebenfalls in den Filter miteinbeziehen.
