### ISSUE TITLE
Alert bei nicht abgeholten Dekreten

### ISSUE THREAD

**Issue by geraldbaeck** [geraldbaeck/NIUsLittleHelper#56]
Dekrete wie zb Dank und Anerkennung, 1000stunden oder Aufahrtenspangen werden oft nicht abgeholt. Im Kommando Menü soll ein dezentes Popup installiert werden, dass eine Warnung ausgibt, wenn einE MitarbeiterIn aufgerufen wird, die noch ein nicht ausgefolgtes Dekret hat. So können die Bezirksstellen ihre Dekrete effizienter verteilen.

Standardmäßig sollte die Funktion ausgeschaltet sein?

**Comment by danielsteiner** [comment]
Nein sollte an sein - zudem sollte man vielleicht auch eine Funktion einbauen die errechnet ob der Mitarbeiter ein Anrecht auf eine Beförderung / Ausfahrten- bzw. Stundenspange hätte.

**Comment by fs1** [comment]
Greift die Funktion auch bei Beförderungen? Da haben wir das gleiche Thema.

**Comment by geraldbaeck** [comment]
greift jetzt auch bei Beförderungen
