### ISSUE TITLE
Liste Ausdruck SAN1 Seminar wird nicht erfasst

### ISSUE THREAD

**Issue by geraldbaeck** [geraldbaeck/NIUsLittleHelper#57]
Bei dern Funktionen der Liste/Ausdruck wird das SAN1 Seminar nicht mehr erfasst, wahrscheinlich weil es voriges Jahr noch SanAmb hieß.

**Comment by danielsteiner** [comment]
Ich glaub das hat einen anderen grund - SanAmb war einfach nur der Verwendungszweck - also fertig mit dem Kurs aber nicht freigegeben. Den Stand gibts jetzt theoretisch nicht mehr
