### ISSUE TITLE
Startseite: Manche KollegInnen werden nicht mehr angezeigt

### ISSUE THREAD

**Issue by geraldbaeck** [geraldbaeck/NIUsLittleHelper#62]
Wenn auf einer Position ein Kollege ist, den man nicht berechtig ist anzuklicken (in diesem Beispiel ein Zivi als San2) dann sieht man von dieser Person gar nix -  also weder Name/Dienstnummer (wie sonst üblich) noch irgendwas
![image](https://user-images.githubusercontent.com/199418/37491519-7230d9b4-289e-11e8-99a7-2de5785b1a34.png)

**Comment by danielsteiner** [comment]
Ich fände es recht cool wenn man das Fotofeature deaktivieren könnte.

**Comment by geraldbaeck** [comment]
Bau ich ein

**Comment by geraldbaeck** [comment]
Layout Änderungen wurden wieder zurückgenommen. Der Server liefert zu oft leere Personenobjekte zurück. Die neue Optik hat nicht den gewünschten Effekt, man müsste die ganze Seite neu designen => nicht unsere Aufgabe. Der praktische Nutzen der Fotos und Vornamen ist im Vergleich zum Aufwand ebenfalls enden wollend.
