### ISSUE TITLE
Ambulanzen: Mannschaftsdaten exportieren

### ISSUE THREAD

**Issue by geraldbaeck** [geraldbaeck/NIUsLittleHelper#65]
Export als CSV mit:

- Vorname
- Nachname
- Dienstnummer
- Position
- Zeiten
- Bemerkung

Möglichst nach Subtag getrennt.

**Comment by danielsteiner** [comment]
Wären nicht Kontaktinfos auch praktisch?

**Comment by geraldbaeck** [comment]
Beim CSV Export sehe ich das Problem, das wir keine sheets für jeden Subtag machen können, müssten wir also eine Datei pro Subtag machen. Ich würde mir vorher auch noch Export nach Google Docs ansehen.

**Comment by geraldbaeck** [comment]
@danielsteiner Jo wären nicht schlecht. Also Email und Telefon. Die Frage ist auch ob bestimmte Berechtigungen interessant wären, wie zb:

- Leerfahrten
- RS-NFR
- GK

**Comment by arminfauland** [comment]
Mit getrennt nach Subtag getrennt meinte ich das es auch ruhig ein Dokument sein kann, das es aber in der Zeile vermerkt ist/steht. Es muss kein eigenes Sheet oder Dokument sein.
Ja persönlich finde ich einen Export nach Google Docs/Sheets gut, aber in der heutigen Zeit mit der DSGVO - grad jetzt in der aufgeheizten Phase - würde ich das mal überdenken.
Gerade wenn wir über persönliche (Kontakt)Daten oder Berechtigungen sprechen - von dem ich übrigens ein großer Fan bin/wäre! :-)

**Comment by geraldbaeck** [comment]
[wiener_halbmarathon_2018_2018_00061.xlsx](https://github.com/geraldbaeck/NIUsLittleHelper/files/1839257/wiener_halbmarathon_2018_2018_00061.xlsx)

Erster Output noch ohne persönliche Daten, Header und Subtage.

**Comment by arminfauland** [comment]
Perfekt! Da werden wir viele glücklich machen! :&)

**Comment by geraldbaeck** [comment]
Ok, Der Export pro Subtag ist online, bitte um Feedback.

**Comment by arminfauland** [comment]
Hi, funktioniert sehr cool!
Danke!
Wir es auch mal möglich sein eine AMB mit mehreren Subtagen auf einmal zu exportieren?

**Comment by geraldbaeck** [comment]
Ich hatte das schon implementiert. Das Problem ist aber, dass bei zu vielen Abfragen der NIU Server irgendwann nichts mehr zurückliefert, deswegen leider derzeit nicht.
