### ISSUE TITLE
Tagesfilter auf der Seite "geplante Dienste"

### ISSUE THREAD

**Issue by arashdalir** [geraldbaeck/NIUsLittleHelper#66]
Liebe Kolleg_innen,
ich hätte einen Vorschlag, und zwar, dass neben den anderen Filterkriterien (wie z.B. Tag- oder Nachtdienste, Leerzeilen Entfernen, usw.) auch 7 checkboxes für die Tage umgesetzt wird. Der Filter könnte besonders den Menschen behilflich sein, die fixe Arbeitsschichten an fixen Wochentagen haben und z.B. nur Mittwochs und Donnerstags Dienste machen können.

ich hätte selbst geschaut, ob ich dieses Feature implementieren könnte, allerdings bin nicht sicher, wie es mit Code-Control angedacht ist, also, ob jeder die Änderungen pushen darf oder ob Ihr ein besonderes System da habt. Daher dachte ich, einmal Euch so zu schreiben wäre vielleicht nicht schlecht.

Vielen Dank und Liebe Grüße,
Arash Dalir, 7105

**Comment by danielsteiner** [comment]
Servus Arash, 

WIr freuen uns immer über Mitarbeit - wenn du die Änderungen selbst implementieren willst kannst du gerne einfach das Repo forken und dann die Änderungen in deinem geforkten Repository testen. Wenn das Feature fertig ist machst du einfach einen Mergerequest, wir schauen uns das Ganze an und wenn es passt wird der Code in die Erweiterung gemerged. 

Wenn du nicht dazu kommst ist das auch kein Problem, dann wird das Feature vermutlich jemand von uns Implementieren.

**Comment by arashdalir** [comment]
Hallo @danielsteiner,
Danke für die Auskunft. Das Feature ist schon implementiert, die "Pull-Request" wurde beantragt.
Danke :smiley:
