### ISSUE TITLE
Export der Mitarbeiter bezogenen Statistik in Kalendereinträge

### ISSUE THREAD

**Issue by phaussl** [geraldbaeck/NIUsLittleHelper#73]
Würde aus eurer Sicht die Möglichkeit bestehen die "Mitarbeiter bezogene Statistik" um einen Kalender Export/Import zu bereichern?

**Comment by phaussl** [comment]
![image](https://user-images.githubusercontent.com/15720890/38026266-cadcab1e-328b-11e8-972d-0912cd548f68.png)

**Comment by geraldbaeck** [comment]
Möglich ist es schon. Entweder als ICS Datei, was wahrscheinlich etwas komplizierter wäre, oder jeden einzelnen Termin, wie auf der Startseite, oder bei den geplanten Diensten.

Was wäre denn Dein Anwendungsfall?

**Comment by phaussl** [comment]
Interessant wäre Beides.

Anwendungsfall:
Ich habe bis in den Dezember Dienste (Permanzen etc.) bereits eingetragen und möchte nicht warten bis die auf der Startseite erscheinen um sie in den Kalender zu übertragen.

Im Moment mach ich das mit einer Digitalen Kopie (Screenshot) der statistik Seite mit der Einstellung (das Monat - Ende des Jahres)

**Comment by danielsteiner** [comment]
Theoretisch möglich aber mmn. nicht praktikabel da es hier zu viel fluktuation gibt. Ist aber definitiv auf der Todo Liste, siehe auch #37 #7 #39

**Comment by phaussl** [comment]
Danke

**Comment by geraldbaeck** [comment]
Bei Permanenzen ist das wirklich ein Problem, wie bei jedem Dienst, den man nicht selbst im NiU einträgt. Man muss sich den den Dienst erst selbst suchen, um ihn über die Extension exportieren zu könnnen. Bei Diensten, für die Du Dich wunschmeldest müsste der Export Button erscheinen. Ambulanzen können auch immer exportiert werden.

Eine ICS für die Statistik wäre ein recht großer Aufwand. Da wäre einen automatische Synchronisierung für Kalender wahrscheinlich wünschenswerter.

**Comment by phaussl** [comment]
Wollt ich auch grad fragen ... ob das nicht machbar wäre :) Syncronisierung mein ich

**Comment by danielsteiner** [comment]
Nope. Dazu müsste entweder das Feature ins NIU eingebaut werden ODER wir brauchen eine API und einen externen Server.

**Comment by phaussl** [comment]
Mit beiden Varianten - vor allem da wir ja auch von persönlichen Daten sprechen - macht man sich mit Sicherheit keine Freunde
