### ISSUE TITLE
v0.52.6, Filter "Nur meldbare Dienste als:" funktioniert nicht mehr

### ISSUE THREAD

**Issue by schwindp** [geraldbaeck/NIUsLittleHelper#76]
"nur Kurzdienste" zB funktioniert, Tag-/Nachtdienste ebenso

-- 
Google Chrome | 65.0.3325.162 (Offizieller Build) (64-Bit)

**Comment by geraldbaeck** [comment]
Leerzeilen filtern funktioniert auch nicht

**Comment by geraldbaeck** [comment]
Übeltäter gefunden, die neue Tagesselektion schaltet die vorher versteckten zeilen auf show. Ich fixe das heute abend.
