### ISSUE TITLE
Verstoß gegen DSGVO

### ISSUE THREAD

**Issue by heinrichmartin** [geraldbaeck/NIUsLittleHelper#90]
Zumindest die Funktion zum Senden von WhatsApp-Nachrichten verstößt gegen die DSGVO, da wir keine Zustimmung haben, MA-Daten an externe Firmen weiterzuleiten.

Das Argument, dass das kein Problem des Plugins bzw des WRK wäre, weil jeder die Telefonnummer auch händisch in WhatsApp eingeben kann, hält nicht: Die NIU ist *kein* persönliches Telefonbuch und kein Social-Media-Portal; es dient zur dienstlichen Kontaktaufnahme.

Diese Darstellung übermittle ich zusätzlich an die Datenschutz-Verantwortlichen.

**Comment by sebastiankuttnig** [comment]
Die Browsererweiterung selbst leitet keine Daten an externe Firmen weiter. Mit der konkreten Funktion wird dem Endbenutzer lediglich die Möglichkeit einer Kontaktaufnahme via WhatsApp ermöglicht, ob er/sie diese nutzt steht dem Endbenutzer frei. Nachdem dies eine clientseitige Erweiterung ist, obliegt meines Erachtens die Einhaltung der DSGVO dem jeweiligen Endbenutzer - ohne dessen aktives Zutun keine Daten weitergeleitet werden. Nach der Logik Ihrer Einschätzung müssten die Entwickler der Copy&Paste Funktion ebenfalls belangt werden, falls diese genutzt wird um unbefugt vertrauliche Daten zu vervielfältigen. Darüber hinaus ist dies generell die falsche Plattform um dienstliche Belange zu klären, daher würde ich Sie  höflich bitten uns über die jeweiligen dienstlichen Kanäle zu kontaktieren. Gerne sind wir bereit Funktionen dieser Erweiterung zu entfernen, sollte ein datenschutzrechtliches bzw. anderes juristisches Gutachten diese als problematisch einstufen.
